package com.imams.boardminton.ui.component.country

import android.content.Context
import com.imams.boardminton.R

fun getCountryName(countryName: String): Int {
    return when (countryName.lowercase()) {
        "ad" -> R.string.andorra
        "ae" -> R.string.united_arab_emirates
        "af" -> R.string.afghanistan
        "ag" -> R.string.antigua_and_barbuda
        "ai" -> R.string.anguilla
        "al" -> R.string.albania
        "am" -> R.string.armenia
        "ao" -> R.string.angola
        "aq" -> R.string.antarctica
        "ar" -> R.string.argentina
        "as" -> R.string.american_samoa
        "at" -> R.string.austria
        "au" -> R.string.australia
        "aw" -> R.string.aruba
        "ax" -> R.string.aland_islands
        "az" -> R.string.azerbaijan
        "ba" -> R.string.bosnia
        "bb" -> R.string.barbados
        "bd" -> R.string.bangladesh
        "be" -> R.string.belgium
        "bf" -> R.string.burkina_faso
        "bg" -> R.string.bulgaria
        "bh" -> R.string.bahrain
        "bi" -> R.string.burundi
        "bj" -> R.string.benin
        "bl" -> R.string.saint_barhelemy
        "bm" -> R.string.bermuda
        "bn" -> R.string.brunei_darussalam
        "bo" -> R.string.bolivia
        "br" -> R.string.brazil
        "bs" -> R.string.bahamas
        "bt" -> R.string.bhutan
        "bw" -> R.string.botswana
        "by" -> R.string.belarus
        "bz" -> R.string.belize
        "ca" -> R.string.canada
        "cc" -> R.string.cocos
        "cd" -> R.string.congo_democratic
        "cf" -> R.string.central_african
        "cg" -> R.string.congo
        "ch" -> R.string.switzerland
        "ci" -> R.string.cote_dlvoire
        "ck" -> R.string.cook_islands
        "cl" -> R.string.chile
        "cm" -> R.string.cameroon
        "cn" -> R.string.china
        "co" -> R.string.colombia
        "cr" -> R.string.costa_rica
        "cu" -> R.string.cuba
        "cv" -> R.string.cape_verde
        "cw" -> R.string.curacao
        "cx" -> R.string.christmas_island
        "cy" -> R.string.cyprus
        "cz" -> R.string.czech_republic
        "de" -> R.string.germany
        "dj" -> R.string.djibouti
        "dk" -> R.string.denmark
        "dm" -> R.string.dominica
        "do" -> R.string.dominican_republic
        "dz" -> R.string.algeria
        "ec" -> R.string.ecuador
        "ee" -> R.string.estonia
        "eg" -> R.string.egypt
        "er" -> R.string.eritrea
        "es" -> R.string.spain
        "et" -> R.string.ethiopia
        "fi" -> R.string.finland
        "fj" -> R.string.fiji
        "fk" -> R.string.falkland_islands
        "fm" -> R.string.micronesia
        "fo" -> R.string.faroe_islands
        "fr" -> R.string.france
        "ga" -> R.string.gabon
        "gb" -> R.string.united_kingdom
        "gd" -> R.string.grenada
        "ge" -> R.string.georgia
        "gf" -> R.string.french_guiana
        "gg" -> R.string.guernsey
        "gh" -> R.string.ghana
        "gi" -> R.string.gibraltar
        "gl" -> R.string.greenland
        "gm" -> R.string.gambia
        "gn" -> R.string.guinea
        "gp" -> R.string.guadeloupe
        "gq" -> R.string.equatorial_guinea
        "gr" -> R.string.greece
        "gt" -> R.string.guatemala
        "gu" -> R.string.guam
        "gw" -> R.string.guinea_bissau
        "gy" -> R.string.guyana
        "hk" -> R.string.hong_kong
        "hn" -> R.string.honduras
        "hr" -> R.string.croatia
        "ht" -> R.string.haiti
        "hu" -> R.string.hungary
        "id" -> R.string.indonesia
        "ie" -> R.string.ireland
        "il" -> R.string.israil
        "im" -> R.string.isle_of_man
        "is" -> R.string.iceland
        "in" -> R.string.india
        "io" -> R.string.british_indian_ocean
        "iq" -> R.string.iraq
        "ir" -> R.string.iran
        "it" -> R.string.italia
        "je" -> R.string.jersey
        "jm" -> R.string.jamaica
        "jo" -> R.string.jordan
        "jp" -> R.string.japan
        "ke" -> R.string.kenya
        "kg" -> R.string.kyrgyzstan
        "kh" -> R.string.cambodia
        "ki" -> R.string.kiribati
        "km" -> R.string.comoros
        "kn" -> R.string.saint_kitts
        "kp" -> R.string.north_korea
        "kr" -> R.string.south_korea
        "kw" -> R.string.kuwait
        "ky" -> R.string.cayman_islands
        "kz" -> R.string.kazakhstan
        "la" -> R.string.laos
        "lb" -> R.string.lebanon
        "lc" -> R.string.saint_lucia
        "li" -> R.string.liechtenstein
        "lk" -> R.string.siri_lanka
        "lr" -> R.string.liberia
        "ls" -> R.string.lesotho
        "lt" -> R.string.lithuania
        "lu" -> R.string.luxembourg
        "lv" -> R.string.latvia
        "ly" -> R.string.libya
        "ma" -> R.string.morocco
        "mc" -> R.string.monaco
        "md" -> R.string.moldova
        "me" -> R.string.montenegro
        "mf" -> R.string.saint_martin
        "mg" -> R.string.madagascar
        "mh" -> R.string.marshall_islands
        "mk" -> R.string.north_macedonia
        "ml" -> R.string.mali
        "mm" -> R.string.myanmar
        "mn" -> R.string.mongolia
        "mo" -> R.string.macau
        "mp" -> R.string.northern_mariana
        "mq" -> R.string.martinique
        "mr" -> R.string.mauritania
        "ms" -> R.string.montserrat
        "mt" -> R.string.malta
        "mu" -> R.string.mauritius
        "mv" -> R.string.maldives
        "mw" -> R.string.malawi
        "mx" -> R.string.mexico
        "my" -> R.string.malaysia
        "mz" -> R.string.mozambique
        "na" -> R.string.namibia
        "nc" -> R.string.new_caledonia
        "ne" -> R.string.niger
        "nf" -> R.string.norfolk
        "ng" -> R.string.nigeria
        "ni" -> R.string.nicaragua
        "nl" -> R.string.netherlands
        "no" -> R.string.norway
        "np" -> R.string.nepal
        "nr" -> R.string.nauru
        "nu" -> R.string.niue
        "nz" -> R.string.new_zealand
        "om" -> R.string.oman
        "pa" -> R.string.panama
        "pe" -> R.string.peru
        "pf" -> R.string.french_polynesia
        "pg" -> R.string.papua_new_guinea
        "ph" -> R.string.philippines
        "pk" -> R.string.pakistan
        "pl" -> R.string.poland
        "pm" -> R.string.saint_pierre
        "pn" -> R.string.pitcairn
        "pr" -> R.string.puerto_rico
        "ps" -> R.string.state_of_palestine
        "pt" -> R.string.portugal
        "pw" -> R.string.palau
        "py" -> R.string.paraguay
        "qa" -> R.string.qatar
        "re" -> R.string.reunion
        "ro" -> R.string.romania
        "rs" -> R.string.serbia
        "ru" -> R.string.russia
        "rw" -> R.string.rwanda
        "sa" -> R.string.saudi_arabia
        "sb" -> R.string.solomon_islands
        "sc" -> R.string.seychelles
        "sd" -> R.string.sudan
        "se" -> R.string.sweden
        "sg" -> R.string.singapore
        "sh" -> R.string.saint_helena
        "si" -> R.string.slovenia
        "sk" -> R.string.slovakia
        "sl" -> R.string.sierra_leone
        "sm" -> R.string.san_marino
        "sn" -> R.string.senegal
        "so" -> R.string.somalia
        "sr" -> R.string.suriname
        "ss" -> R.string.south_sudan
        "st" -> R.string.sao_tome
        "sv" -> R.string.el_salvador
        "sx" -> R.string.sint_maarten
        "sy" -> R.string.syria
        "sz" -> R.string.swaziland
        "tc" -> R.string.turks_and_caicos
        "td" -> R.string.chad
        "tg" -> R.string.togo
        "th" -> R.string.thailand
        "tj" -> R.string.taijikistan
        "tk" -> R.string.tokelau
        "tl" -> R.string.timor_leste
        "tm" -> R.string.turkmenistan
        "tn" -> R.string.tunisia
        "to" -> R.string.tonga
        "tr" -> R.string.turkey
        "tt" -> R.string.trinidad_and_tobago
        "tv" -> R.string.tuvalu
        "tw" -> R.string.taiwan
        "tz" -> R.string.tazmania
        "ua" -> R.string.ukraine
        "ug" -> R.string.uganda
        "us" -> R.string.united_states_america
        "uy" -> R.string.uruguay
        "uz" -> R.string.uzbekistan
        "va" -> R.string.holy_see
        "vc" -> R.string.saint_vincent
        "ve" -> R.string.venezuela
        "vg" -> R.string.virgin_islands
        "vi" -> R.string.virgin_islands_us
        "vn" -> R.string.vietnam
        "vu" -> R.string.vanuatu
        "wf" -> R.string.wallis_and_futuna
        "ws" -> R.string.samoa
        "xk" -> R.string.kosovo
        "ye" -> R.string.yemen
        "yt" -> R.string.mayotte
        "za" -> R.string.south_africa
        "zm" -> R.string.zambia
        "zw" -> R.string.zimbabwe
        else -> R.string.unknown
    }
}

fun getCountries(context: Context): List<Country> = countryNames.map {
    Country(it.key, name = context.getString(it.value), dialCode = "")
}

internal val countryNames: Map<String, Int> = mapOf(
    "ad" to R.string.andorra,
    "ae" to R.string.united_arab_emirates,
    "af" to R.string.afghanistan,
    "ag" to R.string.antigua_and_barbuda,
    "ai" to R.string.anguilla,
    "al" to R.string.albania,
    "am" to R.string.armenia,
    "ao" to R.string.angola,
    "aq" to R.string.antarctica,
    "ar" to R.string.argentina,
    "as" to R.string.american_samoa,
    "at" to R.string.austria,
    "au" to R.string.australia,
    "aw" to R.string.aruba,
    "ax" to R.string.aland_islands,
    "az" to R.string.azerbaijan,
    "ba" to R.string.bosnia,
    "bb" to R.string.barbados,
    "bd" to R.string.bangladesh,
    "be" to R.string.belgium,
    "bf" to R.string.burkina_faso,
    "bg" to R.string.bulgaria,
    "bh" to R.string.bahrain,
    "bi" to R.string.burundi,
    "bj" to R.string.benin,
    "bl" to R.string.saint_barhelemy,
    "bm" to R.string.bermuda,
    "bn" to R.string.brunei_darussalam,
    "bo" to R.string.bolivia,
    "br" to R.string.brazil,
    "bs" to R.string.bahamas,
    "bt" to R.string.bhutan,
    "bw" to R.string.botswana,
    "by" to R.string.belarus,
    "bz" to R.string.belize,
    "ca" to R.string.canada,
    "cc" to R.string.cocos,
    "cd" to R.string.congo_democratic,
    "cf" to R.string.central_african,
    "cg" to R.string.congo,
    "ch" to R.string.switzerland,
    "ci" to R.string.cote_dlvoire,
    "ck" to R.string.cook_islands,
    "cl" to R.string.chile,
    "cm" to R.string.cameroon,
    "cn" to R.string.china,
    "co" to R.string.colombia,
    "cr" to R.string.costa_rica,
    "cu" to R.string.cuba,
    "cv" to R.string.cape_verde,
    "cw" to R.string.curacao,
    "cx" to R.string.christmas_island,
    "cy" to R.string.cyprus,
    "cz" to R.string.czech_republic,
    "de" to R.string.germany,
    "dj" to R.string.djibouti,
    "dk" to R.string.denmark,
    "dm" to R.string.dominica,
    "do" to R.string.dominican_republic,
    "dz" to R.string.algeria,
    "ec" to R.string.ecuador,
    "ee" to R.string.estonia,
    "eg" to R.string.egypt,
    "er" to R.string.eritrea,
    "es" to R.string.spain,
    "et" to R.string.ethiopia,
    "fi" to R.string.finland,
    "fj" to R.string.fiji,
    "fk" to R.string.falkland_islands,
    "fm" to R.string.micronesia,
    "fo" to R.string.faroe_islands,
    "fr" to R.string.france,
    "ga" to R.string.gabon,
    "gb" to R.string.united_kingdom,
    "gd" to R.string.grenada,
    "ge" to R.string.georgia,
    "gf" to R.string.french_guiana,
    "gg" to R.string.guernsey,
    "gh" to R.string.ghana,
    "gi" to R.string.gibraltar,
    "gl" to R.string.greenland,
    "gm" to R.string.gambia,
    "gn" to R.string.guinea,
    "gp" to R.string.guadeloupe,
    "gq" to R.string.equatorial_guinea,
    "gr" to R.string.greece,
    "gt" to R.string.guatemala,
    "gu" to R.string.guam,
    "gw" to R.string.guinea_bissau,
    "gy" to R.string.guyana,
    "hk" to R.string.hong_kong,
    "hn" to R.string.honduras,
    "hr" to R.string.croatia,
    "ht" to R.string.haiti,
    "hu" to R.string.hungary,
    "id" to R.string.indonesia,
    "ie" to R.string.ireland,
    "il" to R.string.israil,
    "im" to R.string.isle_of_man,
    "in" to R.string.india,
    "io" to R.string.british_indian_ocean,
    "iq" to R.string.iraq,
    "ir" to R.string.iran,
    "is" to R.string.iceland,
    "it" to R.string.italia,
    "je" to R.string.jersey,
    "jm" to R.string.jamaica,
    "jo" to R.string.jordan,
    "jp" to R.string.japan,
    "ke" to R.string.kenya,
    "kg" to R.string.kyrgyzstan,
    "kh" to R.string.cambodia,
    "ki" to R.string.kiribati,
    "km" to R.string.comoros,
    "kn" to R.string.saint_kitts,
    "kp" to R.string.north_korea,
    "kr" to R.string.south_korea,
    "kw" to R.string.kuwait,
    "ky" to R.string.cayman_islands,
    "kz" to R.string.kazakhstan,
    "la" to R.string.laos,
    "lb" to R.string.lebanon,
    "lc" to R.string.saint_lucia,
    "li" to R.string.liechtenstein,
    "lk" to R.string.siri_lanka,
    "lr" to R.string.liberia,
    "ls" to R.string.lesotho,
    "lt" to R.string.lithuania,
    "lu" to R.string.luxembourg,
    "lv" to R.string.latvia,
    "ly" to R.string.libya,
    "ma" to R.string.morocco,
    "mc" to R.string.monaco,
    "md" to R.string.moldova,
    "me" to R.string.montenegro,
    "mf" to R.string.saint_martin,
    "mg" to R.string.madagascar,
    "mh" to R.string.marshall_islands,
    "mk" to R.string.north_macedonia,
    "ml" to R.string.mali,
    "mm" to R.string.myanmar,
    "mn" to R.string.mongolia,
    "mo" to R.string.macau,
    "mp" to R.string.northern_mariana,
    "mq" to R.string.martinique,
    "mr" to R.string.mauritania,
    "ms" to R.string.montserrat,
    "mt" to R.string.malta,
    "mu" to R.string.mauritius,
    "mv" to R.string.maldives,
    "mw" to R.string.malawi,
    "mx" to R.string.mexico,
    "my" to R.string.malaysia,
    "mz" to R.string.mozambique,
    "na" to R.string.namibia,
    "nc" to R.string.new_caledonia,
    "ne" to R.string.niger,
    "nf" to R.string.norfolk,
    "ng" to R.string.nigeria,
    "ni" to R.string.nicaragua,
    "nl" to R.string.netherlands,
    "no" to R.string.norway,
    "np" to R.string.nepal,
    "nr" to R.string.nauru,
    "nu" to R.string.niue,
    "nz" to R.string.new_zealand,
    "om" to R.string.oman,
    "pa" to R.string.panama,
    "pe" to R.string.peru,
    "pf" to R.string.french_polynesia,
    "pg" to R.string.papua_new_guinea,
    "ph" to R.string.philippines,
    "pk" to R.string.pakistan,
    "pl" to R.string.poland,
    "pm" to R.string.saint_pierre,
    "pn" to R.string.pitcairn,
    "pr" to R.string.puerto_rico,
    "ps" to R.string.state_of_palestine,
    "pt" to R.string.portugal,
    "pw" to R.string.palau,
    "py" to R.string.paraguay,
    "qa" to R.string.qatar,
    "re" to R.string.reunion,
    "ro" to R.string.romania,
    "rs" to R.string.serbia,
    "ru" to R.string.russia,
    "rw" to R.string.rwanda,
    "sa" to R.string.saudi_arabia,
    "sb" to R.string.solomon_islands,
    "sc" to R.string.seychelles,
    "sd" to R.string.sudan,
    "se" to R.string.sweden,
    "sg" to R.string.singapore,
    "sh" to R.string.saint_helena,
    "si" to R.string.slovenia,
    "sk" to R.string.slovakia,
    "sl" to R.string.sierra_leone,
    "sm" to R.string.san_marino,
    "sn" to R.string.senegal,
    "so" to R.string.somalia,
    "sr" to R.string.suriname,
    "ss" to R.string.south_sudan,
    "st" to R.string.sao_tome,
    "sv" to R.string.el_salvador,
    "sx" to R.string.sint_maarten,
    "sy" to R.string.syria,
    "sz" to R.string.swaziland,
    "tc" to R.string.turks_and_caicos,
    "td" to R.string.chad,
    "tg" to R.string.togo,
    "th" to R.string.thailand,
    "tj" to R.string.taijikistan,
    "tk" to R.string.tokelau,
    "tl" to R.string.timor_leste,
    "tm" to R.string.turkmenistan,
    "tn" to R.string.tunisia,
    "to" to R.string.tonga,
    "tr" to R.string.turkey,
    "tt" to R.string.trinidad_and_tobago,
    "tv" to R.string.tuvalu,
    "tw" to R.string.taiwan,
    "tz" to R.string.tazmania,
    "ua" to R.string.ukraine,
    "ug" to R.string.uganda,
    "us" to R.string.united_states_america,
    "uy" to R.string.uruguay,
    "uz" to R.string.uzbekistan,
    "va" to R.string.holy_see,
    "vc" to R.string.saint_vincent,
    "ve" to R.string.venezuela,
    "vg" to R.string.virgin_islands,
    "vi" to R.string.virgin_islands_us,
    "vn" to R.string.vietnam,
    "vu" to R.string.vanuatu,
    "wf" to R.string.wallis_and_futuna,
    "ws" to R.string.samoa,
    "xk" to R.string.kosovo,
    "ye" to R.string.yemen,
    "yt" to R.string.mayotte,
    "za" to R.string.south_africa,
    "zm" to R.string.zambia,
    "zw" to R.string.zimbabwe,
)
